resolver: lts-3.19
compiler: ghc-7.10.3

packages:
- '.'
#smtlib2 1.0
- location:
    git: https://github.com/hguenther/smtlib2.git
    commit: 5a7f14236ce42e480991dc0c5f2087732fb8b857
  subdirs:
    - '.'
    - backends/debug
    - backends/pipe
    - backends/timing
    - extras/emulated-modulus
  extra-dep: true
#bindings-llvm
- location:
    git: https://github.com/hguenther/bindings-llvm
    commit: c486e76e6c28ae5f4c9718611767789be9eec158
  extra-dep: true

extra-deps:
- atto-lisp-0.2.2.2
- data-fix-0.0.1
- pqueue-1.3.1
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1
