resolver: lts-6.35
compiler: ghc-7.10.3
with-gcc: /usr/bin/gcc-4.9

packages:
- '.'
#smtlib2 1.0
- location:
    git: https://github.com/hguenther/smtlib2.git
    commit: c35747f2a5a9ec88dc7b1db41a5aab6e98c0458d
  subdirs:
    - '.'
    - backends/debug
    - backends/pipe
    - backends/timing
  extra-dep: true
#bindings-llvm
- location:
    git: https://github.com/hguenther/bindings-llvm
    commit: 0b8859720330d3d02cafc915bbd4d79473eafa49
  extra-dep: true
extra-deps:
- atto-lisp-0.2.2.2
- pqueue-1.3.2.3
- turtle-1.5.2
- optparse-applicative-0.14.0.0
- Cabal-1.24.2.0
